import settings from './settings';
import { reactive } from 'vue';

type Localization = Record<string, string>;

const messages: Record<string, Localization> = {
    spanish: {
        creative: "Creativo",
        verycreative: "Muy creativo",
        neutral: "Neutral",
        deterministic: "Deterministico",
        creativity: "Creatividad",
        deleteContact: "Eliminar contacto",
        advertiseMessage: "Advertencia",
        settings: "Configuraciones",
        startToChat: "Selecciona a alguien y comienza a conversar",
        about: "Acerca de Keep Talking",
        send: "Enviar",
        undo: "Deshacer",
        retry: "Reintentar",
        keepTalk: "Keep talk",
        emptyChat: "Vaciar Chat",
        writeSomething: "Escribe algo",
        yourName: "Tu nombre",
        openAIKey: "Open AI API Key",
        defaultModel: "Modelo por defecto",
        deleteAllChats: "Eliminar conversaciones",
        deleteAllContacts: "Eliminar contactos",
        deleteAll: "Eliminar todo",
        user: "Nombre de usuario",
        reachedLimit: "Se ha llegado al tope de mensajes, se vaciará la caja de mensajes en el proximo envío.",
        updates: "Novedades!",
        updateMessage: "Se ha encontrado una nueva versión disponible",
        reload: "Recargar",
        close: "Cerrar",
        addNewContact: "Añadir nuevo contacto",
        contactAdded: "Contacto Añadido",
        photo: "Foto",
        description: "Descripción",
        tags: "Etiquetas",
        done: "Listo",
        confirm: "Confirmar",
        denyResponse: "Lo siento, no puedo responderte en este momento",
        online: "En línea",
        errorToResponse: "No disponible (Error general) ⚠️",
        writting: "Escribiendo...",
        selectLang: "Lenguaje",
        todayIs: "Hoy es",
        saveToFile: "Descargar",
        generalTalkAsk: "¿Sobre qué te gustaría hablar?",
        name: "Nombre contacto",
        reasoningSupport: "Razonamiento",
        areYouSure: "¿Estás seguro?",
        apiEndpoint: "API Endpoint (URL base)",
        apiBaseUrlPlaceholder: "Por ejemplo: https://api.openai.com/v1",
        apiModelPlaceholder: "Por ejemplo: gpt-4o",
        contactImagePlaceholder: "Link de una imagen (no obligatoria)",
        contactNamePlaceholder: "Toda personas tienen un nombre...",
        contactDescriptionPlaceholder: "Algo que diría para iniciar una conversación..",
        defaultUser: "Usuario",
        helpDescription: "Keep Talking utiliza inteligencia artificial para simular conversaciones. Puedes dialogar con personalidades famosas, de alguna serie o hasta algún cantante favorito y pasar un rato, preguntarle o comentarle cosas y recibir una respuesta.",
        helpLimitations: "😬 Limitaciones",
        helpLimitationsDescription: "La inteligencia artifical no es perfecta, a veces puede no seguirte el hilo, ser inconsistente entre respuestas, decir cosas ofensivas y hasta a veces encerrarse en un bucle 😕. Pero tranquilo! Existen opciones para hacer llevadera la experiencia.",
        helpUndo: "Puedes Deshacer/Reformular el último dialogo.",
        helpModify: "Modificar las preferencias del contacto.",
        helpSpecific: "Tratar de ser especifico en tus consultas.",
        helpWarning: "⚠️ Advertencia",
        helpWarningDescription: "El objetivo es divertirse pero siempre es bueno tener algunas consideraciones:",
        helpNotTherapy: "Esto no tiene fines de apoyo terapeutico ni emocionales.",
        helpNotReal: "Recuerda que simplemente estás hablando con un generador de texto, nada es real.",
        helpTechnical: "📚 Aspectos técnicos",
        helpTechnicalDescription: "Esta aplicación se apoya en el modelo de Deep Learning GPT-3 creado por OpenAI, un modelo especializado en la generación de texto por medio de predicciónes de palabras en base a un contexto. Por lo tanto nada de lo que se genere ha sido programado, si no que ha sido producto de un modelo de Deep Learning. Se ha adaptado la entrada del modelo para que analice un esquema tipico conversacional, de esta manera emulando un dialogo.",
        helpTechnicalDescription2: "Si bien GPT-3 fue entrenado en su mayoría con contenido en inglés, maneja muy bien el español con un gran grado de coherencia.",
        helpLocalStoreNote: "**Los historiales de chats y configuraciones se guardan localmente en el navegador y nada de lo que escribas queda registrado en ninguna otra parte.",
        helpCreatedBy: "Creado por",
        poweredBy: "Potenciado por",
        restoreDefaultContacts: "Restaurar contactos por defecto",
        restoreDefaultContactsConfirm: "¿Deseas restaurar los contactos de demostración predeterminados? Esto no borrará tus contactos actuales."
    },
    english: {
        creative: "Creative",
        verycreative: "Very creative",
        neutral: "Neutral",
        deterministic: "Deterministic",
        creativity: "Creativity",
        deleteContact: "Delete contact",
        advertiseMessage: "Advertence!",
        settings: "Settings",
        startToChat: "Choice someone and start chat!",
        about: "About Keep Talking",
        send: "Send",
        undo: "Undo",
        retry: "Retry",
        keepTalk: "Keep talk",
        emptyChat: "Clear chat",
        writeSomething: "Write something",
        yourName: "Your name",
        openAIKey: "Open AI API Key",
        defaultModel: "Default model",
        deleteAllChats: "Delete chats",
        deleteAllContacts: "Delete contacts",
        deleteAll: "Delete all",
        user: "Username",
        reachedLimit: "You reached the limit, the chat will be empty at the next message.",
        updates: "News!",
        updateMessage: "New version is available",
        reload: "Reload",
        close: "Close",
        addNewContact: "Add new contact",
        contactAdded: "Contact added",
        photo: "Photo",
        description: "Description",
        tags: "Tags",
        done: "Done",
        confirm: "Confirm",
        denyResponse: "Sorry, i cant talk now",
        online: "Online",
        errorToResponse: "Offline (General Error) ⚠️",
        writting: "Typing...",
        selectLang: "Language",
        todayIs: "Today is",
        saveToFile: "Save",
        generalTalkAsk: "What would you like to talk about?",
        name: "Name",
        reasoningSupport: "Reasoning",
        areYouSure: "Are you sure?",
        apiEndpoint: "API Endpoint (Base URL)",
        apiBaseUrlPlaceholder: "For example: https://api.openai.com/v1",
        apiModelPlaceholder: "For example: gpt-4o",
        contactImagePlaceholder: "Link to an image (not mandatory)",
        contactNamePlaceholder: "Everyone has a name...",
        contactDescriptionPlaceholder: "Something they would say to start a conversation..",
        defaultUser: "User",
        helpDescription: "Keep Talking uses artificial intelligence to simulate conversations. You can talk to famous personalities, characters from a series, or even your favorite singer and hang out, ask them questions or make comments and receive a response.",
        helpLimitations: "😬 Limitations",
        helpLimitationsDescription: "Artificial intelligence is not perfect; sometimes it may lose the thread, be inconsistent between responses, say offensive things, and even occasionally get stuck in a loop 😕. But don't worry! There are options to make the experience manageable.",
        helpUndo: "You can Undo/Rephrase the last dialogue.",
        helpModify: "Modify the contact's preferences.",
        helpSpecific: "Try to be specific in your queries.",
        helpWarning: "⚠️ Warning",
        helpWarningDescription: "The goal is to have fun, but it's always good to keep some things in mind:",
        helpNotTherapy: "This is not intended for therapeutic or emotional support.",
        helpNotReal: "Remember that you are simply talking to a text generator, nothing is real.",
        helpTechnical: "📚 Technical Aspects",
        helpTechnicalDescription: "This application relies on the GPT-3 Deep Learning model created by OpenAI, a model specialized in text generation through word predictions based on a context. Therefore, nothing that is generated has been programmed; instead, it's the product of a Deep Learning model. The model's input has been adapted to analyze a typical conversational scheme, simulating a dialogue in this way.",
        helpTechnicalDescription2: "While GPT was mostly trained on English content, it handles Spanish very well with a high degree of coherence.",
        helpLocalStoreNote: "**Chat histories and settings are saved locally in the browser, and nothing you write is recorded anywhere else.",
        helpCreatedBy: "Created by",
        poweredBy: "Powered by",
        restoreDefaultContacts: "Restore Default Contacts",
        restoreDefaultContactsConfirm: "Do you want to restore the default demo contacts? This will not delete your current contacts."
    }
};

const text: Localization = reactive({});

const setLang = (lang: string) => {
    Object.keys(text).forEach(key => delete text[key]);
    Object.assign(text, messages[lang] || messages.english);
};

const getLang = () => {
    return settings.language.get();
};

setLang(getLang());

export { text, setLang, getLang };
